version: "3.8"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:8000"
        environment:
            - OPENAI_API_KEY=${OPENAI_API_KEY}
            - PINECONE_API_KEY=${PINECONE_API_KEY}
        env_file:
            - ./.env
